Repository TreinaDev/td11-portfoliorrr, pull requests merged in 2024-02, with the labels that each got.

#67 Feat: Pesquisa projetos do Cola?Bora!
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/projects_controller.rb
  app/controllers/projects_controller.rb
  app/javascript/application.js
  app/javascript/components/projects_vue.js
  app/views/projects/index.html.erb
  app/views/shared/_navbar.html.erb
  config/routes.rb
  spec/support/json/projects.json
  spec/system/projects/user_views_projects_spec.rb
Labels: enhancement

#101 Style/Melhora layout das páginas de seguidores
  app/assets/images/randomuser.jpg
  app/assets/stylesheets/application.bootstrap.scss
  app/helpers/professional_infos_helper.rb
  app/views/connections/_connection_cards.html.erb
  app/views/connections/following.html.erb
  app/views/connections/index.html.erb
  app/views/home/index.html.erb
  config/locales/user.yml
  spec/system/connections/user_views_followers_spec.rb
  spec/system/connections/user_views_following_users_spec.rb
Labels: enhancement

#103 Feat/Cria endpoint da API para consulta completa dos dados do perfil
  api_doc.md
  app/controllers/api/v1/profiles_controller.rb
  app/models/profile.rb
  config/routes.rb
  spec/factories/education_infos.rb
  spec/factories/job_categories.rb
  spec/factories/professional_infos.rb
  spec/factories/profile_job_categories.rb
  spec/requests/apis/v1/profile_full_info_api_spec.rb
Labels: enhancement

#96 [ FEAT ] Usuario solicita convite para projeto
  app/assets/stylesheets/application.bootstrap.scss
  app/controllers/projects_controller.rb
  app/javascript/application.js
  app/javascript/components/projects_vue.js
  app/models/invitation_request.rb
  app/models/profile.rb
  app/models/user.rb
  app/views/projects/index.html.erb
  app/views/shared/_navbar.html.erb
  config/locales/invitation_request.pt-BR.yml
  config/routes.rb
  db/migrate/20240201165511_create_invitation_requests.rb
  db/migrate/20240202194430_remove_email_from_invitation_request.rb
  db/schema.rb
  spec/factories/invitation_requests.rb
  spec/models/invitation_request_spec.rb
  spec/requests/invitation_requests/user_creates_invitation_request_spec.rb
  spec/system/projects/user_request_project_invitation_spec.rb
  spec/system/projects/user_views_projects_spec.rb
Labels: enhancement

#109 Feat/perfil publico ou privado
  app/controllers/api/v1/profiles_controller.rb
  app/controllers/profiles_controller.rb
  app/models/profile.rb
  app/views/connections/_connection_cards.html.erb
  app/views/profile/_profile.html.erb
  app/views/profiles/show.html.erb
  config/locales/profile.pt-BR.yml
  config/routes.rb
  db/migrate/20240204213733_add_column_privacy_to_profile.rb
  db/schema.rb
  spec/factories/personal_infos.rb
  spec/system/profiles/user_changes_profile_to_private_spec.rb
  spec/system/profiles/user_changes_work_status_spec.rb
Labels: enhancement

#146 Adiciona o consumo da API que recusa o convite na Colabora
  app/controllers/invitations_controller.rb
  app/jobs/decline_invitation_job.rb
  app/models/invitation.rb
  app/views/invitations/index.html.erb
  app/views/invitations/show.html.erb
  config/locales/invitation.pt-BR.yml
  db/schema.rb
  spec/jobs/decline_invitation_job_spec.rb
  spec/system/invitations/user_declines_invitations_spec.rb
Labels: enhancement

#153 [Fix] Resolve bug do teste `ActiveStorage::Blob`
  spec/system/profile_photo/user_edits_profile_photo_spec.rb
Labels: bug

#155 Adiciona foto de perfil como dropdown ao invés de placeholder
  app/assets/images/user-solid.svg
  app/views/profiles/show.html.erb
  app/views/shared/_navbar.html.erb
Labels: enhancement

#134 Envio de e-mail com resumo diário de curtidas recebidas pelo usuário
  .gitignore
  app/jobs/daily_likes_digest_job.rb
  app/mailers/likes_mailer.rb
  app/models/like.rb
  app/models/user.rb
  app/views/likes_mailer/notify_like.html.erb
  config/environments/development.rb
  config/environments/test.rb
  db/schema.rb
  spec/factories/posts.rb
  spec/jobs/daily_likes_digest_job_spec.rb
  spec/mailers/likes_mailer_spec.rb
  spec/spec_helper.rb
  spec/system/authentication/visitor_sign_up_spec.rb
  spec/system/likes/user_likes_spec.rb
Labels: enhancement

#164 Feat/desativar conta
  app/controllers/api/v1/profiles_controller.rb
  app/controllers/application_controller.rb
  app/controllers/home_controller.rb
  app/controllers/profiles_controller.rb
  app/models/profile.rb
  app/views/profiles/settings.html.erb
  app/views/profiles/show.html.erb
  app/views/shared/_navbar.html.erb
  config/locales/devise.pt-BR.yml
  config/locales/profile.pt-BR.yml
  config/routes.rb
  db/migrate/20240208192517_add_status_to_profiles.rb
  db/migrate/20240209144343_add_old_status_to_posts.rb
  db/migrate/20240209150412_add_old_name_to_user.rb
  db/schema.rb
  spec/models/profile_spec.rb
  spec/requests/apis/v1/profile_full_info_api_spec.rb
  spec/requests/profiles/user_deactivate_profile_spec.rb
  spec/system/authentication/visitor_logs_in_spec.rb
  spec/system/comments/user_comments_blog_post_spec.rb
  spec/system/connections/user_views_following_users_spec.rb
  spec/system/profiles/user_views_other_user_profile_spec.rb
  spec/system/searches/users_searchs_others_users_spec.rb
  spec/system/settings/user_views_profile_settings_spec.rb
Labels: enhancement

#167 Fix/Remove extensão de arquivos na listagem de posts
  app/helpers/posts_helper.rb
  app/views/posts/_listing.html.erb
  app/views/posts/show.html.erb
  db/schema.rb
  spec/system/comments/user_comments_blog_post_spec.rb
  spec/system/posts/user_views_post_list_spec.rb
  spec/system/posts/visitor_views_post_spec.rb
Labels: enhancement

#175 Fix/Adiciona cobertura de teste adicional ao project_controller
  spec/requests/apis/v1/searches_projects_spec.rb
Labels: enhancement

#178 Fix/Data de publicação se torna obrigatoria para publicação programada
  app/models/post.rb
  spec/requests/reports/user_reports_spec.rb
  spec/system/connections/user_views_followers_spec.rb
  spec/system/posts/user_creates_post_spec.rb
  spec/system/posts/user_edits_post_spec.rb
Labels: bug

#161 [Feature] Criação de proposal no Cola?Bora! ao preencher formulário de solicitação de convite no Portfoliorrr
  app/controllers/api/v1/projects_controller.rb
  app/jobs/request_invitation_job.rb
  app/models/invitation_request.rb
  app/models/profile.rb
  config/locales/invitation_request.pt-BR.yml
  config/routes.rb
  db/migrate/20240209192701_add_status_to_invitation_request.rb
  db/schema.rb
  lib/exceptions.rb
  spec/jobs/request_invitation_job_spec.rb
  spec/rails_helper.rb
  spec/requests/apis/v1/projects/projects_request_invitations_api_spec.rb
  spec/support/json/proposal_201.json
  spec/system/projects/user_request_project_invitation_spec.rb
Labels: documentation

#180 Refactor/Ajuste na tela de configurações
  app/controllers/profiles_controller.rb
  app/controllers/settings_controller.rb
  app/views/profiles/show.html.erb
  app/views/settings/index.html.erb
  config/locales/profile.pt-BR.yml
  config/locales/settings.pt-BR.yml
  config/routes.rb
  spec/system/profiles/user_changes_work_status_spec.rb
  spec/system/settings/user_changes_profile_to_private_spec.rb
  spec/system/settings/user_changes_work_status_spec.rb
  spec/system/settings/user_views_profile_settings_spec.rb
Labels: enhancement

#183 Fix/permite busca com e sem acentuação
  app/models/profile.rb
  app/models/user.rb
  db/migrate/20240212172630_add_search_name_to_users.rb
  db/schema.rb
Labels: enhancement

#179 [ FEATURE ] Notificações em postagens de interesse
  app/assets/stylesheets/application.bootstrap.scss
  app/jobs/post_interest_notification_job.rb
  app/models/comment.rb
  app/views/notifications/_comment.html.erb
  app/views/notifications/_connection.html.erb
  app/views/notifications/_invitation.html.erb
  app/views/notifications/index.html.erb
  app/views/posts/show.html.erb
  config/locales/notifications.pt-BR.yml
  config/solid_queue.yml
  db/schema.rb
  spec/jobs/notify_posts_of_interests_spec.rb
  spec/system/notifications/user_is_notified_about_post_of_interest_spec.rb
Labels: enhancement

#197 [ REFACT ] Refatora Likes Controller
  app/controllers/comments/likes_controller.rb
  app/controllers/likes_controller.rb
  app/controllers/posts/likes_controller.rb
  app/views/posts/show.html.erb
  config/locales/likes.pt-BR.yml
  config/routes.rb
  db/schema.rb
  spec/requests/likes/user_likes_spec.rb
Labels: enhancement

#189 Refactor/melhora layout do perfil
  app/assets/images/about-icon.svg
  app/assets/images/book-half.svg
  app/assets/images/briefcase-solid.svg
  app/assets/images/person-fill.svg
  app/assets/images/person-working.svg
  app/assets/images/pin-angle-fill.svg
  app/assets/images/pin-angle.svg
  app/assets/images/user-graduate-solid.svg
  app/assets/stylesheets/application.bootstrap.scss
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/navbar.scss
  app/assets/stylesheets/posts.scss
  app/assets/stylesheets/profile.scss
  app/helpers/personal_infos_helper.rb
  app/views/posts/_listing.html.erb
  app/views/profile/_personal_info.html.erb
  app/views/profiles/_personal_info.html.erb
  app/views/profiles/_profile_details.html.erb
  app/views/profiles/_profile_photo.html.erb
  app/views/profiles/show.html.erb
  config/locales/education_info.pt-BR.yml
  config/locales/models/personal_info.pt-BR.yml
  config/locales/models/posts.pt-BR.yml
  config/locales/models/professional_info.pt-BR.yml
  config/locales/profile.pt-BR.yml
  db/migrate/20240212193006_add_default_visibility_to_personal_info.rb
  db/schema.rb
  db/seeds.rb
  spec/system/education_info/user_creates_education_info_spec.rb
  spec/system/posts/user_edits_post_spec.rb
  spec/system/professional_info/user_creates_professional_info_spec.rb
  spec/system/profile/user_views_profile_spec.rb
Labels: enhancement

#202 Feat/api endpoint recusa solicitação convite
  api_doc.md
  app/controllers/api/v1/invitation_request_controller.rb
  config/locales/models/invitation_request.pt-BR.yml
  config/routes.rb
  spec/requests/apis/v1/invitation_requests/leader_denies_invitation_request_spec.rb
Labels: enhancement

#221 [Setup] Configura MailCatcher e Procfile.dev
  Procfile.dev
  README.md
  config/environments/development.rb
Labels: enhancement

#224 Feat/responder comentário
  app/assets/stylesheets/application.bootstrap.scss
  app/controllers/posts_controller.rb
  app/controllers/replies/likes_controller.rb
  app/controllers/replies_controller.rb
  app/controllers/reports_controller.rb
  app/models/comment.rb
  app/models/reply.rb
  app/models/user.rb
  app/views/home/index.html.erb
  app/views/posts/show.html.erb
  app/views/reports/index.html.erb
  app/views/shared/_navbar.html.erb
  config/locales/pt-BR.yml
  config/locales/replies.pt-BR.yml
  config/routes.rb
  db/migrate/20240213185205_create_replies.rb
  db/schema.rb
  spec/factories/likes.rb
  spec/factories/replies.rb
  spec/models/reply_spec.rb
  spec/system/comments/user_reply_to_blog_comment_spec.rb
  spec/system/likes/user_likes_spec.rb
  spec/system/reports/user_report_spec.rb
Labels: enhancement

#249 [ FEAT ] Anúncios no feed de usuários free
  app/controllers/advertisements_controller.rb
  app/controllers/home_controller.rb
  app/models/advertisement.rb
  app/models/user.rb
  app/views/advertisements/_advertisement.html.erb
  app/views/advertisements/index.html.erb
  app/views/advertisements/new.html.erb
  app/views/advertisements/show.html.erb
  app/views/posts/_listing.html.erb
  app/views/shared/_navbar.html.erb
  config/locales/buttons.pt-BR.yml
  config/locales/models/advertisement.pt-BR.yml
  config/routes.rb
  db/migrate/20240215195415_create_advertisements.rb
  db/schema.rb
  spec/factories/advertisements.rb
  spec/models/advertisement_spec.rb
  spec/requests/advertisements/user_visits_advertisements_page_spec.rb
  spec/system/advertisements/admin_create_ad_spec.rb
  spec/system/advertisements/user_sees_ads_spec.rb
Labels: enhancement
